language: rust

rust:
    - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

addons:
  apt:
    packages:
      - nasm

install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install pygments --user
  - pip install pygments-github-lexers --user

script: bash scripts/travis-build.sh

after_success: sh scripts/travis-blog-update.sh
