[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "restful_os"
version = "0.1.0"

[dependencies]
bit_field = "0.7.0"
bitflags = "0.7.0"
multiboot2 = "0.3.2"
once = "0.3.2"
rlibc = "1.0.0"
spin = "0.4.5"
volatile = "0.1.0"
x86 = "0.8.1"
x86_64 = "0.1.2"
atomic = "0.3.4"



[dependencies.log]
default-features = false
version = "0.3.7"

[dependencies.heap_irq_safe]
path = "libs/heap_irq_safe"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "0.2.1"

[dependencies.keycodes_ascii]
path = "libs/keycodes_ascii"

[dependencies.port_io]
path = "libs/port_io"
version = "0.2.1"

[dependencies.irq_safety]
path = "libs/irq_safety"
version = "0.1.1"
# features = ["const_fn"]  #if we need them later

[dependencies.dfqueue]
path = "libs/dfqueue"
version = "0.1.0"


[lib]
crate-type = ["staticlib"]
