baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Writing an OS in Rust"
rssURI = "atom.xml"

[params]
  subtitle = "Philipp Oppermann's blog"
  author = "Philipp Oppermann"
  date_format = "Jan 2, 2006"
