[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "panic_unwind"
version = "0.1.0"

[dependencies]


# [dependencies.vga_buffer]
# path = "../vga_buffer"

# [build]
# rustflags = ["-C", "prefer-dynamic", "-C", "panic=abort"]


[lib]
crate-type = ["lib"]
