[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "nano_core"
version = "0.1.0"

[dependencies]
bit_field = "0.7.0"
bitflags = "0.7.0"
multiboot2 = "0.3.2"
once = "0.3.2"
rlibc = "1.0.0"
spin = "0.4.5"
volatile = "0.1.0"
x86 = "0.8.1"
x86_64 = "0.1.2"
atomic = "0.3.4"
xmas-elf = "0.6.0"

# this is needed for our odd approach of including the nano_core as a library for other kernel crates
# compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" } #unsure if needed



[dependencies.log]
default-features = false
version = "0.3.7"

[dependencies.heap_irq_safe]
path = "../../libs/heap_irq_safe"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "0.2.1"

[dependencies.keycodes_ascii]
path = "../../libs/keycodes_ascii"

[dependencies.port_io]
path = "../../libs/port_io"
version = "0.2.1"

[dependencies.irq_safety]
path = "../../libs/irq_safety"
version = "0.1.1"
# features = ["const_fn"]  #if we need them later

[dependencies.dfqueue]
path = "../../libs/dfqueue"
version = "0.1.0"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.state_store]
path = "../state_store"

[dependencies.serial_port]
path = "../serial_port"

[dependencies.logger]
path = "../logger"

[dependencies.vga_buffer]
path = "../vga_buffer"

[dependencies.test_lib]
path = "../test_lib"

[build]
rustflags = ["-C", "link-args=-fPIC", "-C", "relocation-model=pic", "-C", "code-model=large"]


[lib]
# this builds both libtheseus.a and libtheseus.rlib
# staticlib is required to build a self-contained .a file that we can boot into
# rlib is for my hopeful attempt to satisfy the collections and other dependencies when building other crates as dylibs

# we choose rlib, because according to https://doc.rust-lang.org/reference/linkage.html, a dynamic library cannot be converted into static,
# meaning that all "upstream dependencies are required to be in rlib format", so this must be rlib to other crates can be built against it
# Furthermore we cannot build it as a dylib instead of rlib because he custom x86_64-theseus target triple doesn't support it (really, Xargo doesn't support it)
crate-type = ["staticlib", "rlib"]  

