[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "nano_core"
description = "The minimalist crate that takes over after the bootloader and is responsible for pre-initialization of Theseus, before handing off control to the captain"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
cfg-if = "1.0.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
spin = "0.4.10"
multiboot2 = "0.7.1"
# x86_64 = { git = "https://github.com/kevinaboos/x86_64" }
x86_64 = { path = "../../libs/x86_64" } # currently using our local copy, forked from Phil Opp's crate

[target.'cfg(target_arch = "x86_64")'.dependencies.log]
version = "0.4.8"

[target.'cfg(target_arch = "x86_64")'.dependencies.kernel_config]
path = "../kernel_config"

[target.'cfg(target_arch = "x86_64")'.dependencies.irq_safety]
git = "https://github.com/kevinaboos/irq_safety"

[target.'cfg(target_arch = "x86_64")'.dependencies.logger]
path = "../logger"

[target.'cfg(target_arch = "x86_64")'.dependencies.state_store]
path = "../state_store"

[target.'cfg(target_arch = "x86_64")'.dependencies.memory]
path = "../memory"

[target.'cfg(target_arch = "x86_64")'.dependencies.stack]
path = "../stack"

[target.'cfg(target_arch = "x86_64")'.dependencies.mod_mgmt]
path = "../mod_mgmt"

[target.'cfg(target_arch = "x86_64")'.dependencies.exceptions_early]
path = "../exceptions_early"

[target.'cfg(target_arch = "x86_64")'.dependencies.captain]
path = "../captain"

[target.'cfg(target_arch = "x86_64")'.dependencies.panic_entry]
path = "../panic_entry"

[target.'cfg(target_arch = "x86_64")'.dependencies.vga_buffer]
path = "../vga_buffer"

[target.'cfg(target_arch = "x86_64")'.dependencies.memory_initialization]
path = "../memory_initialization"

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m-rt = "0.6.13"
cortex-m-semihosting = "0.3.7"
panic-halt = "0.2.0"
alloc-cortex-m = "0.4.1"

[target.'cfg(target_arch = "arm")'.dependencies.cortex-m]
features = ["inline-asm"]
version = "0.6.4"


[lib]
# staticlib is required to build a self-contained, fully-linked .a file 
# that we can jump to from the bootloader.
crate-type = ["staticlib"]  

