[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "test_client"
version = "0.1.0"

[dependencies]
test_server = { path = "../test_server" }

[lib]
crate-type = ["rlib"] # "lib" does the same thing I think
