[package]
authors = ["Bowen Liu <liubowenbob@hotmail.com>"]
name = "usb_device"
version = "0.1.0"


[dependencies]
[dependencies.usb_desc]
path = "../usb_desc"

[dependencies.usb_req]
path = "../usb_req"



[lib]
crate-type = ["rlib"] # "lib" does the same thing I think
