[workspace]


## We don't really need this "members" element, but to use the features of a crate
## we must include that crates as a member.
members = [
	"nano_core",
]

[features]
loadable = [ "nano_core/loadable", "captain/loadable" ]
mirror_serial = [ "nano_core/mirror_serial" ]
apic_timer_fixed = [ "apic/apic_timer_fixed" ]
