[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "memory_structs"
description = "Common types used in the memory management subsystem"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
zerocopy = "0.3.0"
cfg-if = "1.0.0"

[dependencies.derive_more]
version = "0.14.0"
default-features = false
features = [ "no_std" ]

[dependencies.kernel_config]
path = "../kernel_config"

[target.'cfg(target_arch = "x86_64")'.dependencies.entryflags_x86_64]
path = "../entryflags_x86_64"

[target.'cfg(target_arch = "x86_64")'.dependencies.bit_field]
version = "0.7.0"

[lib]
crate-type = ["rlib"]
