[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "console"
description = "A console (terminal emulator) implementation"
version = "0.1.0"

[dependencies]
spin = "0.4.5"
# x86_64 = { git = "https://github.com/kevinaboos/x86_64" }
x86_64 = { path = "../../libs/x86_64" }


[dependencies.keycodes_ascii]
path = "../../libs/keycodes_ascii"

[dependencies.vga_buffer]
path = "../vga_buffer"

[dependencies.dfqueue]
path = "../../libs/dfqueue"
version = "0.1.0"

[dependencies.console_types]
path = "../console_types"

[dependencies.nano_core]
path = "../nano_core"

[lib]
crate-type = ["rlib"] # "lib" does the same thing I think
