[package]
name = "usb_driver"
version = "0.1.0"
authors = ["BowenLiu15 <bl28@rice.edu>"]

[dependencies]

[dependencies.owning_ref]
# version = "0.3.3"
# path = "../../libs/owning-ref-rs"
git = "https://github.com/kevinaboos/owning-ref-rs.git"

[dependencies.usb_device]
path = "../usb_device"

[dependencies.log]
default-features = false
version = "0.3.7"

[dependencies.usb_uhci]
path = "../usb_uhci"

[dependencies.usb_ehci]
path = "../usb_ehci"

[dependencies.usb_desc]
path = "../usb_desc"

[dependencies.usb_req]
path = "../usb_req"

[dependencies.memory]
path = "../memory"

[dependencies.usb_keyboard]
path = "../usb_keyboard"