[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "serial_port"
version = "0.1.0"

[dependencies.port_io]
path = "../../libs/port_io"

[lib]
crate-type = ["rlib"] # "lib" does the same thing I think