[package]
name = "usb_keyboard"
version = "0.1.0"
authors = ["BowenLiu15 <bl28@rice.edu>"]

[dependencies]
spin = "0.4.5"
volatile = "0.2.4"

[dependencies.owning_ref]
# version = "0.3.3"
# path = "../../libs/owning-ref-rs"
git = "https://github.com/kevinaboos/owning-ref-rs.git"


[dependencies.usb_device]
path = "../usb_device"

[dependencies.log]
default-features = false
version = "0.3.7"

[dependencies.usb_uhci]
path = "../usb_uhci"

[dependencies.usb_ehci]
path = "../usb_ehci"

[dependencies.usb_desc]
path = "../usb_desc"

[dependencies.memory]
path = "../memory"

[dependencies.keycodes_ascii]
path = "../../libs/keycodes_ascii"