[package]
name = "usb_uhci"
version = "0.1.0"
authors = ["BowenLiu15 <bl28@rice.edu>"]


[dependencies]
spin = "0.4.5"
raw-cpuid = "3.0.0"
volatile = "0.2.4"
# x86_64 = { git = "https://github.com/kevinaboos/x86_64" }
x86_64 = { path = "../../libs/x86_64" } # currently using our local copy, forked from Phil Opp's crate
atomic = { version = "0.3.4", features = ["nightly"]}

[dependencies.log]
default-features = false
version = "0.3.7"

[dependencies.pci]
path = "../pci"

[dependencies.owning_ref]
# version = "0.3.3"
# path = "../../libs/owning-ref-rs"
git = "https://github.com/kevinaboos/owning-ref-rs.git"


[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.0"

[dependencies.irq_safety]
git = "https://github.com/kevinaboos/irq_safety"
version = "0.1.1"

[dependencies.port_io]
path = "../../libs/port_io"

[dependencies.atomic_linked_list]
path = "../../libs/atomic_linked_list"

[dependencies.pit_clock]
path = "../pit_clock"

[dependencies.memory]
path = "../memory"

[dependencies.spawn]
path = "../spawn"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.usb_device]
path = "../usb_device"


[dependencies.usb_desc]
path = "../usb_desc"


[lib]
crate-type = ["rlib"] # "lib" does the same thing I think
