[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "vga_buffer"
version = "0.1.0"

[dependencies]
rlibc = "1.0.0"
spin = "0.4.5"
volatile = "0.1.0"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "0.2.1"

[dependencies.serial_port]
path = "../serial_port"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.state_store]
path = "../state_store"


# [build]
# rustflags = ["-C", "prefer-dynamic", "-C", "panic=abort"]


[lib]
crate-type = ["rlib"] # "lib" does the same thing I think